name: Deploy to Staging

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase db push --db-url "postgresql://postgres:${{ secrets.STAGING_DB_PASSWORD }}@db.${{ secrets.STAGING_PROJECT_ID }}.supabase.co:5432/postgres"
